### ISSUE TITLE
How to input c code file in picrypt

### ISSUE THREAD

**Issue by djsakisd** [minosg/picrypt#1]
Hi minosg can you please add a tutorial on how to include another c code file in picrypt in order to protect it ?

Please keep it simple for noobs.

**Comment by minosg** [comment]
The point of this tool is to not directly bind with your code, but to encrypt a folder/ directory and all its contents and only unlock it on the device it was compiled. 

Assuming you completed the information in the authorized hardware, and compiled a picrypt binary,  you can just encrypt a direcotory with the command bellow:

sudo picrypt --encrypt /opt/your_awesome_code

Then after reboot the directory will only be mountable by

sudo picrypt --mount /opt/your_awesome_code

And if you are in a rasbian/debian installation or any that has systemd you can set it to automount using
sudo make automount_add target=/opt/your_awesome_code 


(called from your picrypt directory)

It is planned to add a screencast of a simple compilation soon.

**Comment by minosg** [comment]
I have just uploaded screen casts to demonstrate on how to protect a directory using the tool.
